version: '3'
services:
    emitter:
        image: accretio-hub.advyteam.com/emitter:2.1.7
        environment:
           - EMITTER_PROFILE=prod
            - MONGODB_HOST=accretio-mongodb
            - MONGODB_PORT=27017
            - MONGODB_DATABASE=uaa
            - MONGODB_USERNAME=uaauser
            - MONGODB_PASSWORD=useruaa&2017
            - GATEWAY_HOST=gateway
            - GATEWAY_PORT=8080
        ports:
            - "8084:8084"
            - "8089:8089"
